language: java
sudo: false
os:
- linux
jdk:
- oraclejdk8
env:
  matrix:
  - GROUP=1s
  - GROUP=mzn
  - GROUP=xcsp
  - GROUP=mps
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - choco@emn.fr
    on_success: always
    on_failure: always
script: mvn clean install -DtestFailureIgnore=true -Dgroups=$GROUP
after_success:
- bash <(curl -s https://codecov.io/bash)
